# Generated by Django 6.0.6 on 2026-06-13 09:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='0 dan katta son kiriting !!!'), django.core.validators.MaxValueValidator(100, message=' 100 dan kichik son kiriting !!!')], verbose_name='Qavat')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Tugallangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaxti')),
            ],
            options={
                'verbose_name': 'Bino',
                'verbose_name_plural': 'Binolar',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('location', models.CharField(max_length=250, verbose_name='Joylashuvi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaxti')),
            ],
            options={
                'verbose_name': 'Kompaniya',
                'verbose_name_plural': 'Kompaniyalar',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message="18 yoshga to'lganlarni uchun mumkin !!!")], verbose_name='Yosh')),
                ('job', models.CharField(max_length=250, verbose_name='Kasb')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oylik')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaxt')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.building', verbose_name='Bino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='main.company', verbose_name='Kompaniya'),
        ),
        migrations.AddField(
            model_name='building',
            name='workers',
            field=models.ManyToManyField(related_name='buildings', to='main.worker', verbose_name='Ishchilar'),
        ),
    ]
